name: Repository Sync

on:
  schedule:
    # Runs every two weeks
    - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run add_submodule script
        id: add_submodule
        continue-on-error: true
        run: |
          python scripts/add_submodule.py

      - name: Run populate_md script
        if: steps.add_submodule.conclusion == 'success'
        run: |
          python scripts/populate_md.py
        
      - name: Commit changes
        if: steps.add_submodule.conclusion == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet || git add README.md
          git diff --cached --quiet || git commit -m 'Update README.md with new lab links'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Record last successful run time
        if: steps.add_submodule.conclusion == 'success'
        run: |
          echo "{\"schemaVersion\": 1, \"label\": \"Last Last Synced\", \"message\": \"$(date -u)\", \"color\": \"success\"}" > .github/last_success.json
          git add .github/last_success.json
          git commit -m "Update last synced run time"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}