name: Update README.md

on:
  schedule:
    # Runs every two weeks
    - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run add_submodule script
        id: add_submodule
        run: |
          python scripts/add_submodule.py

      - name: Run populate_md script
        if: steps.add_submodule.outcome == 'success'
        run: |
          python scripts/populate_md.py

      - name: Commit changes
        if: steps.add_submodule.outcome == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README.md with new lab links'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}